apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: donjoee/udagram-api-feed:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: uda-configmap
            - secretRef:
                name: envsecret
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: uda-configmap-aws
      volumes:
        - name: uda-configmap-aws
          configMap:
            name: uda-configmap-aws