apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: donjoee/udagram-api-feed:v0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: uda-configmap
            - secretRef:
                name: envsecret
